### ISSUE TITLE
Generated sprites have lots of empty space at bottom right corner 

### ISSUE THREAD

**Issue by minevala** [Ensighten/spritesmith#48]
I'm using gulp.spritesmith to generate sprites.
I've noticed recently a large empty area at right bottom corner of the sprites.
Root cause might be:   "layout": "~2.0.0" --> "layout": "~2.1.0".
I'm using mac OSX 10.10.1

**Comment by twolfson** [comment]
Yep, we switched our binary packing algorithm but everything should have more/less remained the same. Can you provide us with a copy of the sprites or the dimensions of said images?

**Comment by minevala** [comment]
Here is link to sprite: https://github.com/minevala/icons/blob/master/sprite.png

**Comment by twolfson** [comment]
That's the generated spritesheet. We need the sprites themselves to reproduce. Otherwise, it is a very tedious manual process.

**Comment by minevala** [comment]
There are the files and the sprite https://github.com/minevala/icons

**Comment by twolfson** [comment]
Awesome, thanks! I will take a look at this by the end of the weekend.

**Comment by twolfson** [comment]
A fix has been merged and released in `spritesmith@1.2.0`, `grunt-spritesmith@3.9.0`, and `gulp.spritesmith@2.8.0`. Thanks for the bug report!

**Comment by minevala** [comment]
Nice :+1:
