### ISSUE TITLE
Is there any possibility to modify the generated mixins?

### ISSUE THREAD

**Issue by fernandofleury** [Ensighten/spritesmith#58]
I would like to modify the `background-image: url` to use the sass helper `image-url`

I didn't find much related to stylesheet generation, and was wondering if that is possible.

**Comment by twolfson** [comment]
I can't seem to find any documentation on `image-url`. Can you provide a link to me?

**Comment by fernandofleury** [comment]
https://github.com/sass/node-sass/releases/tag/v3.0.0-pre

It seems like I'm using an old version of `node-sass` still supporting it. Will close the issue and keep using `imagePath` option. Sorry for the inconvenience.

**Comment by twolfson** [comment]
Ah, k. No worries =)

**Comment by twolfson** [comment]
I should mention that there are ways to customize templates:

- Override the mixins themselves (e.g. redefine `sprite`, redefine a lower level mixin, or make a new one)
- Create your own template (either by extending an existing one or starting from scratch)
    - This can be done via `cssTemplate` in the `grunt-spritesmith`/`gulp.spritesmith` options
    - Here's the existing SCSS one: https://github.com/twolfson/spritesheet-templates/blob/10.0.0/lib/templates/scss.template.handlebars
