### ISSUE TITLE
deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.

### ISSUE THREAD

**Issue by roninliu** [Ensighten/spritesmith#59]
deprecated pngjs2@1.2.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.

could you fixed?

**Comment by twolfson** [comment]
I'm not sure what dependency you are talking about, there are no direct dependencies to `pngjs` in this repo =/

https://github.com/Ensighten/spritesmith/blob/2.0.1/package.json#L32-L52
