### ISSUE TITLE
Add padding around boundary area

### ISSUE THREAD

**Issue by Moonshell** [Ensighten/spritesmith#63]
When I cut icon images align it's boundary, and then found display problems on some android devices browser. 
The sprite image looks like this: (dark area means padding of spritesmith)
![01](https://cloud.githubusercontent.com/assets/4216470/14772799/cfd21040-0ad4-11e6-9603-72ca8433df3b.png)

So I have to keep another padding when I cut the images, to achieve the effect like that:
![02](https://cloud.githubusercontent.com/assets/4216470/14772813/fb418a4e-0ad4-11e6-9deb-dabaa0cdf703.png)

It's boring and not effective, could spritesmith help me add the boundary padding like that? It whill solve my big problem, thx~

**Comment by twolfson** [comment]
Could you elaborate on the problem you are encountering?

**Comment by Moonshell** [comment]
For example, the icon images might look like this:
![image](https://cloud.githubusercontent.com/assets/4216470/14774191/fa8c7652-0ae5-11e6-9f1c-2752cb1f8c84.png)
And then join them into the sprites images:
![image](https://cloud.githubusercontent.com/assets/4216470/14774207/1c0158d4-0ae6-11e6-8bcc-f613c6a9d439.png)
The problem arises:
![image](https://cloud.githubusercontent.com/assets/4216470/14774178/cf170d8e-0ae5-11e6-8b0b-ae18b2f941d0.png)
The yellow icon is in the right bottom corner, but it might mix up with the icon right top and left bottom.

**Comment by twolfson** [comment]
Ah, I see. Setting `background-repeat: no-repeat` in the CSS should resolve that. It's caused by scaling images and why we initially introduced `padding` as an option:

https://github.com/Ensighten/spritesmith/issues/7

**Comment by Moonshell** [comment]
Oh, I forgot adding it to my automatic tasks... Maybe this problem won't show on most android devices again, thank you!

**Comment by twolfson** [comment]
I'm glad that resolved that issue =)
