### ISSUE TITLE
Fatal error: Ran out of data

### ISSUE THREAD

**Issue by padjodev** [Ensighten/spritesmith#65]
I keep getting this error Fatal error: Ran out of data

I have about 10 small enough pics in a folder and if i add any more i get this error

**Comment by twolfson** [comment]
Can you try using the test images and see what happens?

https://github.com/Ensighten/spritesmith/tree/3.1.0/src-test/test_sprites

**Comment by padjodev** [comment]
Hey.. managed to track down the issue.. answered my own stackoverflow Q here

http://stackoverflow.com/questions/37883172/grunt-fatal-error-ran-out-of-data?noredirect=1#comment63221292_37883172

**Comment by twolfson** [comment]
Ah, neat. Glad to hear the problem is resolved =)
