### ISSUE TITLE
Support `glob` in src

### ISSUE THREAD

**Issue by evilebottnawi** [Ensighten/spritesmith#66]

**Comment by twolfson** [comment]
It's an interesting thought but I think we should pass. It will break backwards compatibility with any files that contain a `*` in their name as well as add unnecessary code/dependencies. Someone can use `glob` before passing along `src` to `spritesmith`:

```js
var glob = require('glob');
Spritesmith.run({
  src: glob.sync('path/to/files/*.png'),
  ...
}, function () { /* ... */ })
```

**Comment by evilebottnawi** [comment]
@twolfson `sync` is not good solution it is slow then async, we have big build and async (speed) is very important

**Comment by twolfson** [comment]
The example was sync but async can be used as well:

```js
var glob = require('glob');
glob('path/to/files/*.png', function handleGlob (err, files) {
  // If there was an error, handle it as desired
  if (err) {
    throw err;
  }

  // Call spritesmith
  Spritesmith.run({
    src: files,
    ...
  }, function () { /* ... */ })
});
```

**Comment by evilebottnawi** [comment]
@twolfson I would like to have this opportunity to base, but if this is not feasible so sorry
