### ISSUE TITLE
Feature request: client library that decodes a sprite-sheet and outputs images

### ISSUE THREAD

**Issue by iONinja** [Ensighten/spritesmith#74]
Hi there.

I like the idea of the Node.js library, but it would be great to have a nice utility on the client as well that can decode this information. This client-side library would take the sprite-sheet and JSON coordinate map, and spit out the separate images in some form.

Thanks!

**Comment by twolfson** [comment]
This feels like another project altogether. Going to close this as a `wontfix` but here's tools that would help you get started on it:

- https://github.com/scijs/get-pixels (load an image into its pixel equivalents)
- https://github.com/scijs/ndarray (for extracting the subimages from the pixels)
- https://github.com/scijs/save-pixels (save an array of pixels back into an image)

**Comment by iONinja** [comment]
@twolfson 
Okay, I might make a new project implementing both sides or something.
Those tools look good, but it seems like HTML5 Canvas would be easier? Would you recommend Canvas as an option?

**Comment by twolfson** [comment]
Yep, canvas is another viable option 👍
